-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "lowStockAlert" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "reservedStock" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "stockQty" INTEGER NOT NULL DEFAULT 0;
